package-lock.json
package.json
src/router/index.js
src/views/Dashboard.vue
src/views/Home.vue
src/views/Login.vue

:sparkles: introduce meta-data

---

package-lock.json
src/views/Login.vue
tests/unit/views/Login.spec.js

introduce offline for login page
I add somes tests to see how it could work with. It seems nice. I'd appreciate some feedbacks about that.

:sparkles: introduce offline for login page

---

README.md

(Because it's more beautiful) 👌 👌

:lipstick: Align title and images in README

---

docs/CODEOWNERS.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md

Add code owner and code of conduct

:memo: Add code owner and code of conduct

---

docs/CONTRIBUTING.md

Fix contributing typo Frank into Franck

:pencil2: Fix contributing typo

---

docs/CONTRIBUTING.md

Add slack in contributing documentation

:memo: Add slack in contributing documentation

---

public/service-worker.js
src/App.vue
src/components/NewContentAvailableToastr.vue
src/misc/register-service-worker.js
src/store/app/app.actions.js
src/store/app/app.getters.js
src/store/app/app.mutations.js
src/store/app/app.state.js
tests/unit/store/app/app.actions.spec.js
tests/unit/store/app/app.getters.spec.js
tests/unit/store/app/app.mutations.spec.js

See #134 
This SW workflow is much better to handle the "new content available" workflow
Thanks @NOtherDev for the suggestion :pray: I'd love to get your review !

:sparkles: Update service worker skipWaiting workflow

---

.firebaserc
package.json
src/components/NavBar.vue
src/theme/variables.scss
vue-config/config.default.js
vue-config/config.production.js

:fire: Enable hashcontent name for generated files

---

package.json

:bug: Fix prettier commands execution for windows

---

babel.config.js
package-lock.json
package.json
src/firebase/async-firestore.js
src/firebase/authentication.js
src/firebase/generic-db.js
src/misc/handle-apple-install-prompt.js
src/router/index.js
src/store/app/app.actions.js
src/store/app/app.getters.js
src/store/authentication/authentication.actions.js
src/store/authentication/authentication.getters.js
src/views/CheckLogin.vue
src/views/Login.vue
tests/unit/store/products/products.mutations.spec.js
tests/unit/views/Login.spec.js

:art: Improve lodash imports with babel-plugin-lodash

---

internals/setup.js

See #158 
**TODO before merge**

:sparkles: Improve setup command

---

internals/helpers/git-helper.js
internals/setup.js
package-lock.json

externalize git command in setup

:recycle: externalize git command in setup

---

package-lock.json

:arrow_up: Upgrade bundlesize dependencies

---

internals/helpers/git-helper.js

This fixes the windows command issue on first time pull. This will work on all platforms.
This is for issue #191

:bug: Fix setup command for windows environment

---

src/components/ProductDetail.vue
src/components/ProductItem.vue
src/router/index.js
src/store/products/products.getters.js
src/views/Product.vue

#177 
⚠️ This is the first time I've used `vuex`

:sparkles: Add product details page

---

package-lock.json
package.json

:arrow_up: Upgrade lodash

---

firebase.json

Boosting performances score and helping load time by adding Styles (css) and Scripts (js) to the hosting headers and changing the max-age value.

:wrench: Add source and update max-age value for hosting Headers

---

.all-contributorsrc
README.md

:busts_in_silhouette: Add a contributor

---

.firebaserc
.github/workflows/ci.yml
.github/workflows/deploy-production.yml
README.md
package-lock.json
package.json
src/main.js
src/misc/register-service-worker.js

:construction_worker: Add Github Actions

---

internals/helpers/clean-useless-resources.js

update resource paths to avoid removing github actions during setup

:wrench: fixes #247
